#!/usr/bin/env bash
# ===========================================================================
# Launch a V5.5 stage inside the project's own tmux socket.
#
# Usage: v55_launch.sh <stage-tag> <script-to-run>
#
# Two measured constraints on this host drive the design (tmux 1.8, from 2014):
#   1. ``new-session`` accepts only a SINGLE command word -- passing the script
#      plus arguments prints the usage line and creates nothing.
#   2. tmux 1.8 does NOT propagate the parent environment into the session, so
#      V55_LOG cannot simply be exported (verified: the child saw V55_PROBE=UNSET).
#
# Therefore this launcher GENERATES a single-file wrapper per stage with the log
# path and target baked in, and hands tmux exactly one path.  The wrapper sources
# tools/v55_env.sh itself, so nothing needs to cross the tmux boundary.
#
# Placeholders use the unambiguous @@TOKEN@@ form (never __X__), because the
# generated script legitimately uses shell variables like $__LOG__ and a
# __[A-Z]*__ pattern check would flag those as unsubstituted.
# ===========================================================================
set -uo pipefail
WS=/data/raw/huzijian/project1_database
SOCK="$WS/tmp/tmux_v55.sock"
TOOLS="$WS/tools"

STAGE="${1:?usage: v55_launch.sh <stage-tag> <script>}"
SCRIPT="${2:?usage: v55_launch.sh <stage-tag> <script>}"
SESSION="p1_v55_${STAGE}"
LOG="$WS/tmp/v55_${STAGE}.out"
GEN="$TOOLS/run_v55_${STAGE}.sh"
RC="$WS/tmp/v55_${STAGE}.rc"

if tmux -S "$SOCK" has-session -t "$SESSION" 2>/dev/null; then
  echo "session $SESSION ALREADY EXISTS -- not launching a duplicate"
  tmux -S "$SOCK" ls
  exit 0
fi

[ -f "$SCRIPT" ] || { echo "target script not found: $SCRIPT"; exit 2; }

# Keep the previous log rather than deleting it (V5.5 forbids deletion).
if [ -f "$LOG" ]; then
  mv "$LOG" "$LOG.prev.$(date +%Y%m%dT%H%M%S)"
fi

cat > "$GEN" <<'TEMPLATE'
#!/usr/bin/env bash
# GENERATED by v55_launch.sh -- safe to regenerate. Do not hand-edit.
# Single file, no arguments: tmux 1.8 accepts only one command word.
LOG_FILE="@@LOG@@"
RC_FILE="@@RC@@"
exec >"$LOG_FILE" 2>&1
echo "=== V5.5 stage @@STAGE@@ ==="
echo "start   : $(date -Is)"
echo "host    : $(hostname)"
echo "wrapper : $0"
echo "target  : @@TARGET@@"
# tmux 1.8 does not forward the parent env, so construct it here.
source "@@TOOLS@@/v55_env.sh"
cd "$REPO" || { echo "cannot cd to $REPO"; echo 1 > "$RC_FILE"; exit 1; }
echo "cwd     : $(pwd)"
echo "python  : $("$PY" -V 2>&1)"
echo "blender : $BLENDER"
echo "=========================================="
bash "@@TARGET@@"
rc=$?
echo "=========================================="
echo "end     : $(date -Is)"
echo "rc      : $rc"
echo "$rc" > "$RC_FILE"
exit $rc
TEMPLATE

# Substitute placeholders literally (values contain '/' so use an alternate delimiter).
sed -i \
  -e "s|@@LOG@@|${LOG}|g" \
  -e "s|@@RC@@|${RC}|g" \
  -e "s|@@STAGE@@|${STAGE}|g" \
  -e "s|@@TARGET@@|${SCRIPT}|g" \
  -e "s|@@TOOLS@@|${TOOLS}|g" \
  "$GEN"
chmod +x "$GEN"

# Sanity: no placeholder may survive, and the result must parse.
if grep -q '@@[A-Z]*@@' "$GEN"; then
  echo "GENERATION FAILED: unsubstituted placeholder in $GEN"
  grep -n '@@[A-Z]*@@' "$GEN"
  exit 3
fi
bash -n "$GEN" || { echo "GENERATION FAILED: $GEN has a syntax error"; exit 3; }

tmux -S "$SOCK" new-session -d -s "$SESSION" "$GEN"

echo "launched : session=$SESSION"
echo "socket   : $SOCK"
echo "log      : $LOG"
echo "wrapper  : $GEN"
sleep 6
echo "--- tmux ls ---"
tmux -S "$SOCK" ls 2>&1
echo "--- log ---"
cat "$LOG" 2>&1
