"""Archive the previous runtime build into remove/ with a hash-verified manifest.

The project forbids deleting files. Rebuilding the layered runtime copy overwrites the previous
one in place, so the previous copy is first moved to `remove/` together with a manifest of every
file's SHA-256 and size. That keeps the no-deletion rule true by evidence rather than by intent, and
it also means a rebuild that turns out to be worse can be reverted.
"""

from __future__ import annotations

import hashlib
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(r"D:\workspace\project1_database")
SRC = Path(sys.argv[1]) if len(sys.argv) > 1 else (
    ROOT / "outcomes/v55/scenes/italian_flat/runtime")
LABEL = sys.argv[2] if len(sys.argv) > 2 else "runtime_pre_floor"


def sha256(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> int:
    if not SRC.exists():
        print(f"nothing to archive: {SRC} does not exist")
        return 0
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    dest = ROOT / "remove" / f"{LABEL}_{stamp}"
    dest.mkdir(parents=True, exist_ok=True)
    manifest = {"archived_from": str(SRC), "archived_to": str(dest),
                "reason": ("the layered runtime copy is regenerated by tools/v55_build_layers.py; "
                           "the previous build is preserved rather than overwritten in place, "
                           "because this project deletes nothing"),
                "utc": stamp, "files": []}
    total = 0
    # A FILE source must be handled explicitly: `Path.rglob` on a file yields nothing, so an earlier
    # version archived zero files while printing "all hashes verified: True" -- vacuously true over
    # an empty list -- and left the source in place. That is a silent success report on a no-op, so
    # the file case is now first-class and the empty case is reported as a failure rather than a pass.
    if SRC.is_file():
        members = [(SRC, Path(SRC.name))]
    else:
        members = [(p, p.relative_to(SRC)) for p in sorted(SRC.rglob("*")) if p.is_file()]
    for p, rel in members:
        target = dest / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        digest = sha256(p)
        size = p.stat().st_size
        shutil.move(str(p), str(target))
        after = sha256(target)
        manifest["files"].append({
            "relative_path": rel.as_posix(), "bytes": size, "sha256_before": digest,
            "sha256_after_move": after, "hash_verified": digest == after,
        })
        total += size
        print(f"  moved {rel.as_posix():46s} {size:>12d} B  hash {'OK' if digest == after else 'MISMATCH'}")
    manifest["file_count"] = len(manifest["files"])
    manifest["total_bytes"] = total
    # `all([])` is True, which would report success for having moved nothing. archiving nothing is
    # never a success: either the source was empty (a mistake worth surfacing) or the path was wrong.
    manifest["all_hashes_verified"] = bool(manifest["files"]) and all(
        f["hash_verified"] for f in manifest["files"])
    (dest / "MANIFEST.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"\narchived {manifest['file_count']} files ({total/1e6:.2f} MB) -> {dest}")
    print(f"all hashes verified: {manifest['all_hashes_verified']}")
    print(f"manifest: {dest / 'MANIFEST.json'}")
    if not manifest["files"]:
        print(f"FAILURE: {SRC} contained no files, so nothing was archived and nothing was moved. "
              f"An archive that moves nothing must not report success.")
        return 1
    return 0 if manifest["all_hashes_verified"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
